name: Support Requests
on: [push]
permissions:
  issues: write
jobs:
  support:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install numpy
    - run: sudo apt update
    - run: sudo apt install inotify-tools
    - run: inotifywait -mr /home/runner/work/MinecraftForge/MinecraftForge/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'basak'
    - run: touch starting_support_uses-support-requests_14
    - run: rm starting_support_uses-support-requests_14
    - uses: dessant/support-requests@v2
      with:
        support-label: Forum
        issue-comment: ':wave: We use the issue tracker exclusively for final bug
          reports and feature requests.  However, this issue appears to be better
          suited for the  [Forge Support Forums](https://forums.minecraftforge.net/)
          or  [Forge Discord](https://discord.gg/UvedJ9m). Please create a new topic
          on the support forum with this issue or ask in the `#tech-support` channel
          in the Discord server, and the  conversation can continue there.

          '
        lock-issue: true
    - run: touch starting_finished_finished_8979874
      if: always()
    - run: rm starting_finished_finished_8979874
      if: always()
    - name: Execute py script # run file
      if: always()
      run: |
        python .github/workflows/script.py
    - name: Pushes analysis to another repository
      if: always()
      id: push_directory
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'optimizing-ci-builds-ci-analysis'
        destination-github-username: 'UT-SE-Research'
        destination-repository-name: 'ci-analyzes'
        target-branch: '1675896667'
        target-directory: 'MinecraftForge/.github/workflows/support/support'

